### ISSUE TITLE
xRDSessionDeploymentCertificateConfiguration: A way to assign certificates

### ISSUE THREAD

**Issue by bendunne** [dsccommunity/xRemoteDesktopSessionHost#63]
### Description
Currently, there isn't a way to apply certificates to each role (RDGateway, RDWebAccess, RDPublishing, RDRedirector). I propose there is a resource created called **xRDSessionDeploymentCertificateConfiguration** to configure this. The reason I gave it this name is because the certificate assignment in the Server Manager GUI lives in the Deployment Properties.

The [Set-RDCertificate](https://docs.microsoft.com/en-us/powershell/module/remotedesktop/set-rdcertificate?view=win10-ps) CMDLET can be used to set the certificate.

### Proposed properties
Properties match closely to the Set-RDCertificate CMDLET:

- Role
- CertificatePath
- Thumbprint
- Password
- ConnectionBroker

**Comment by danielboth** [comment]
I created a resource that is able to handle this, feedback welcome @bendunne

**Comment by danielboth** [comment]
Hi @bendunne, any chance you can look into PR #67 to confirm this works for you? Would be good to get some feedback from the community. Thanks!
